import { chromium } from 'playwright';
const OUT='/home/user/subtime/scripts/shots/rv';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const ctx=await b.newContext({viewport:{width:375,height:667},deviceScaleFactor:2});
const p=await ctx.newPage(); p.on('dialog',d=>d.accept());
await p.goto('http://localhost:4173'); await p.waitForSelector('text=Sub Time');
await p.click('text=+ New team'); await p.fill('input[placeholder="Thunder"]','T');
await p.selectOption('.sheet select','9'); await p.click('text=Create team');
await p.waitForSelector('text=Roster · 0'); await p.click('text=+ Add player');
const N=['Ana Ruiz','Bea Okonjo','Cal Nguyen','Dee Marsh','Eli Vance','Fin Doyle','Gus Park','Hal Rivera','Ivy Chen','Jo Adeyemi','Kit Larsen','Lou Bianchi'];
for(let i=0;i<12;i++){await p.fill('input[inputmode="numeric"]',String(i+1));await p.fill('#player-name',N[i]);await p.click('.sheet .btn.primary');await p.waitForTimeout(15);}
await p.click('.sheet >> text=Close');
await p.click('text=+ New game'); await p.click('text=Create game');
await p.waitForSelector("text=Who's here?"); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-attendance.png`});
await p.click('.sheet >> text=Done'); await p.waitForSelector('.sheet-backdrop',{state:'detached'});
await p.click('.token >> nth=0'); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-pickplayer.png`});
await p.click('.sheet >> text=Close');
await p.click('text=Fill rest'); await p.waitForTimeout(200);
await p.click('text=Start game'); await p.waitForSelector('.pitch');
await p.click('[aria-label="Start clock"]'); await p.waitForTimeout(1500);
await p.click('text=⚽ Us'); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-goal.png`});
await p.click('.sheet .chip >> nth=0'); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-assist.png`});
await p.click('.sheet .chip >> nth=0'); await p.waitForTimeout(400);
await p.click('[aria-label="More"]'); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-menu.png`});
await p.click('.sheet >> text=Close');
await p.click('[aria-label="Event log"]'); await p.waitForTimeout(700);
await p.screenshot({path:`${OUT}/s-log.png`});
await b.close();
